### PR TITLE
Remove preventDefault() when the popup closed

### PR DESCRIPTION
**Pull request by Sielc**
Fix for #153, it's tested and works

### CODE REVIEW

**Comment by darrenjennings** [comment]
Thanks for the PR! The code coverage CI failure is fine, I will dismiss, but I'm more concerned with having a test. Do you feel up to writing one?

**Comment by Sielc** [comment]
No, I don't understand what exactly you want to cover with a test and how to do it.

**Comment by Sielc** [comment]
Did you checked changes and understood why preventDefault() works correct now? Will you merge this PR?

**Comment by darrenjennings** [comment]
Yea needs tests, so will get to that when I can.

**Comment by Sielc** [comment]
hey, how are you?)

**Comment by darrenjennings** [comment]
@Sielc i had to make some tweaks to your code, but went ahead and bundled this into PR #164 in favor of releasing it without back and forth of PR review. Thanks for the contribution!

**Comment by Sielc** [comment]
Hi, @darrenjennings 
I checked your code and saw changes helping our problem. Great! Thank you.
Just to be sure, did you checked that 'enter' key doesn't preventDefault() when the popup is closed?

As you can see in my diff, I added a check for key 13
```
case 13: // Enter
     if (this.isOpen) {
           e.preventDefault();
```
But you didn't

**Comment by darrenjennings** [comment]
@Sielc I haven't published a new version yet, I'll be sure to get that in for you.

**Comment by darrenjennings** [comment]
@Sielc try `vue-autosuggest@2.0.4-beta.0` and let me know if this solves your issue.

**Comment by Sielc** [comment]
> @Sielc try `vue-autosuggest@2.0.4-beta.0` and let me know if this solves your issue.

I tried and it didn't worked. Will investigate 'why?' later

**Pull request closed without merging**
